### ISSUE TITLE
Apple Watch App Issue

### ISSUE THREAD

**Issue by madsights** [megabitsenmzq/PomoNow-iOS#3]
The apple watch app doesn't follow the same settings set within the iOS app. It simply counts down one pomodoro and one break. Then it restarts and you must use the crown to run through another new pomodoro. Completely ignoring the long break time and long break delay settings. Unless i'm missing something?

**Comment by megabitsenmzq** [comment]
The watch app will follow pomodoro and break time settings within iOS app. And it does ignore long break, and won’t restart timer automatically. Because of the limit of watch OS, I don’t know how to do it now.
Debugging on watch OS is really difficult. I don’t have enough time to add more function on it now. Maybe I will work on it latter.

**Comment by madsights** [comment]
That’s too bad, bit of a deal breaker for me. Nice app design wise though. I like what you’ve done with it.

– Ryan

**Comment by megabitsenmzq** [comment]
Thank you. I will continue improve the watch app when I have enough time.

**Comment by madsights** [comment]
Please do. Just to get it running through the full pomodoro cycle and long breaking would be great.

– Ryan

**Comment by megabitsenmzq** [comment]
Please check PomoNow 2.10 on App Store. Now PomoNow watch can run full pomodoro cycle and add task on watch.
